title: timothyae.com
description: Official website of Timothy Escopete
baseurl: ""
url: "https://timothyae.com"

permalink: pretty

exclude: [
  "node_modules/",
  "*.gemspec",
  "*.gem",
  "Gemfile",
  "Gemfile.lock",
  "package.json",
  "package-lock.json",
  "script/",
  "LICENSE.txt",
  "lib/",
  "bin/",
  "README.md",
  "Rakefile",
]

# Set a path/url to a logo that will be displayed instead of the title.
# logo: "/assets/images/logo.png"

# Enable or disable the site search.
# Supports true (default) or false.
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors.
heading_anchors: true

# Aux links for the upper right navigation.
aux_links:
  "timothy on Github":
    - "//github.com/timhtheos"
  "timothy on Drupal.org":
    - "//www.drupal.org/u/timhtheos"

# Makes Aux links open in a new tab. Default is false.
aux_links_new_tab: false

# Sort order for navigation links.
nav_sort: case_sensitive

# Footer content
# appears at the bottom of every page's main content.

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This site uses a fork version of <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a>, a documentation theme for Jekyll, by Patrick Marsceill."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/timhtheos/timothy"
gh_edit_branch: "master"
#gh_edit_source: docs
# Edit view mode: "tree" or "edit" if you want the user to jump into the editor immediately.
gh_edit_view_mode: "tree"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define.
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-10
# Use GDPR compliant Google Analytics settings (true/nil by default)
ga_tracking_anonymize_ip: true

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false
#   # ignore:
#   #   envs: all
compress_html:
  ignore:
    envs: all

disqus:
  handle: timhtheos
  url:
    old:  timothy.sh
    new:  timothyae.com
